### ISSUE TITLE
Broken Commit Causing Puppet Code Manager to Break

### ISSUE THREAD

**Issue by scrothers** [puppetlabs/puppetlabs-dsc#210]
This repository is causing an issue using Puppet Enterprise 2016.1.2 and code manager.

I have set in my Puppetfile the following:
> mod 'puppetlabs/dsc', '1.0.1'

Once that get's picked up by code manager, the attached exception spams out of control in my puppet server and no deployments get picked up. 

I have attached the exception and also the small shell script I use to fix the problem and re-deploy in case it is useful to anybody else in my gist.

https://gist.github.com/scrothers/827af0c6ea1a1912eb4164829006cb3d

**Comment by jpogran** [comment]
Thanks for the report @scrothers. This isn't a problem with the dsc module, but a known issue in 2016.1.2, which has been fixed in 2016.2.0 and also there is a workaround to use until you can upgrade. https://support.puppet.com/hc/en-us/articles/219376108 has all the information related to this. Any questions, don't hesitate to let us know.

**Comment by glennsarti** [comment]
@scrothers Are you ok to close this close?

**Comment by scrothers** [comment]
Yep, sorry, fixed it the other day and I meant to reply but my active sprint got in the way. Thanks!
