### ISSUE TITLE
Support ps dsc resources deployement via chocolatey 

### ISSUE THREAD

**Issue by msutter** [puppetlabs/puppetlabs-dsc#224]
Hi All,

Just had a look in your changes since last year.
Looks good, you did a great job 👍 

Just wondering why you choose to deploy the powershell code of the dsc modules via puppetx sync in a specific location and not using the default location for ps modules ($pshome/modules).

As we are PS5 ready now at the company i'm working at, I'm in the process of updating the dsc module in our infra. I still want to be able to build external puppet dsc modules, based on our own custom powershell dsc modules. We did this by automating the build of a chocolatey package for our custom powershell dsc modules and we're using the package resource (with the chocolatey provider) to install them on the target machine before using the generated puppet dsc_x resources in our puppet modules. Hope it's clear enough.....

I really like the new features (pscredentials and shared ps sessions) thanks, but I still want to be able to split the puppet dsc modules. Is someone working on this ? When not could you create a ticket for me that a can make a appropriate git branch to work on ?

I've identified 3 points to be implemented:

- Option to choose if we want to use the puppetx or the $pshome/modules location when invoking the dsc run
-  Option to choose if we want to include the dsc ps code in the module, enabling the option of a alternative deployment of the ps module.
- Option to pull/clone custom dsc modules as git submodules

Tell me what you think about these enhancements please.

Cheers
Marc

**Comment by msutter** [comment]
To be more precise:

Make use of a config file when dealing with custom resources with following options:
- the location of the ps dsc modules to load at runtime (puppetx or $pshome/modules)
- disabling the copying of the ps dsc code in the puppet module at build time (https://github.com/puppetlabs/puppetlabs-dsc/blob/master/build/dsc.rake#L72)
- Allowing to import custom module code from a git repo (like the DSCResources with git submodules)

All these config settings could be set with defaults to match your current workflow.
There is already such a config file we could use (https://github.com/puppetlabs/puppetlabs-dsc/blob/master/build/dsc.yaml)

Marc

**Comment by Iristyle** [comment]
Hi Marc - 

I can give you a bit of the backstory on why and how we vendor resources - our choices were pretty intentional.

* We didn't want users to be concerned with installing DSC resources themselves through an alternate mechanism - the PS gallery doesn't have a story yet around mirroring / it may be difficult for machines without Internet access to acquire upstream DSC resources.  We opted for a better user experience at the cost of having to provide regular updates to this module incorporating updated vendored resources.
* Since we vendor actual DSC resource implementations, we are bound to an interface at the time that the type and provider wrappers were generated.  Given `x` prefixed resources change their MOF schema often, we're only safe with using what the schema defined at build time.  The only place where we would be certain this could work is for the resources that are part of WMF5 (which we don't vendor anyhow).
* We didn't want to modify what's already in the "SYSTEM" DSC resources, because we want to isolate the implementation we've built against what users may already have installed.  I think it would be surprising for users to see us overwrite existing DSC resources in a globally shared path if they were transitioning from DSC to Puppet on their machines.
* We found that DSC resources can be loaded by our vendored path, which is basically what allows to safely provide a side-by-side experience.
* PowerShell doesn't like `Import-Module` being called on directories that have modules of the same name.

So I think that this module as released + a different set of DSC resource implementations is a potentially dangerous operation.

Our model thus far for custom resources is to support a workflow on top of this module, that allows you to change versions of the DSC resources vendored + allows building wrappers for your custom DSC resources as well:
https://github.com/puppetlabs/puppetlabs-dsc/blob/master/README_BUILD.md

Really, the module is designed to always carry with it the DSC resource files - all the `MOF` / `psm1` / etc files in a neat package alongside the Puppet implementation, so everything is synced to a well known set of implementations.



So as I understand your main issue - you want to use different DSC resource implementations alongside the module.

* I think we can find additional mechanisms of "importing" resources during a build - we can look into a Git model in addition to what we already provide
* It is technically possible to add extra search paths for our `Import-Module` calls, but this seems to be of dubious value.  If you need the wrapper types generated by the build process in your Puppet manifests, and necessarily need a custom version of the module - why would you want to pull the DSC resource implementations back out and release those separately?  That seems like additional work that can create an "out of sync" situation.  
FWIW: I think the extra search does make more sense once we have a generic DSC wrapper helper - but we're not there yet (and honestly haven't had anyone ask us for it).

Maybe if you could expand more on why you wish to build the type wrappers, but don't want to include them within the custom module... that would help us understand your situation better?


Thanks for the ideas!

**Comment by msutter** [comment]
Hi Ethan,

Thanks for your interesting feedback.

Our concern is in the continuous integration/deployment area. As a big company we've a lot of IT engineers, working in their own area. Windows engineers working on DSC resources only and Linux/Puppet engineers working on the puppet manifests. It was difficult in early 'puppet for windows' days to merge this 2 worlds. We had a lot of powershell code included in the puppet modules as files or templates and the exec resource was hardly used. Development, debugging and testing was extremely hard for our windows guys, as they had to know how to use linux, puppet, hieradata, and all the stuff around a puppet run to work on a simple windows configuration item. 

This is the reason why I initially started the DSC Puppet Module. Allowing our teams to define a common interface around the DSC resources and working, most of the time, in their own area.
Our windows guys are now able the develop custom DSC resources, test them with pester and build them in a chocolatey package ready to be installed in our environments without any puppet skills.

Apart from that our puppet infrastructure is designed with a puppet master tree. We've at the moment more than 50 puppet masters (Open Source) all connected together. This is why we 'split' our dsc puppet modules. We use the main dsc module with only the base type and the provider. Every new dsc resource has it's own puppet module to host the generated types. This allows us to only deploy the features in the environment (puppet master) who needs them. Deploying a change in just a single DSC resource means now updating all of our masters with the new monolithic generated DSC Puppet module.

I understand your points, and fully agree with the choices you took. It make sense to include the powershell code in the module who's using it to keep it in sync. I can adapt the deployment of the powershell code to be included in the puppet module, but I absolutely need an option to host our custom dsc modules in their own puppet module. Ideally by pulling the code from Git.

Long story......

I'll fork the project, make a branch and modify the rake tasks to be able to build an external dsc puppet module for custom resources so that we can build an extension to the dsc module with its own types and powershell code in puppetx.

Thanks for your time.
Cheers
Marc

**Comment by Iristyle** [comment]
Thanks Marc - that definitely explains your situation better.

I think we're all in favor of improving the "customization" experience and we'll take the details of your use case into consideration for future developments.  We definitely want you to be able to point at a Git repo to import your custom PowerShell resources, and I think there are some things we can discuss internally on how to allow more configurable packaging of the customizations.  If you want to notify us when you've forked your changes, a PR would be great for us to take a look at.

FWIW - We have seen a few other cases of the "develop outside of Puppet" workflow, specifically around PowerShell.  During testing of PowerShell exec code, people want to be able to use something like Pester and verify their PS locally, then drop it into an exec like `& my-pscode.ps1`, rather than turning it into a Puppet template, etc.  It's an interesting workflow.


Thanks again for the feedback - we'll do our best to work on a solution here.

**Comment by glennsarti** [comment]
@msutter Are you happy for my to close this issue?

**Comment by msutter** [comment]
@glennsarti sure, i'll make a PR when my changes are ready.

**Comment by glennsarti** [comment]
Thanks again @msutter.
