### ISSUE TITLE
xSQLServer needs to be upgraded to 5.0.0.0

### ISSUE THREAD

**Issue by shotah** [puppetlabs/puppetlabs-dsc#284]
Can I get help with this error? Currently trying to install MS SQL 2016 through the DSC resource. 
```Error: PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource functionality with error messa
ge: 'SSMS' is not a valid value for setting 'FEATURES'.  Refer to SQL Help for more information.
Error: /Stage[main]/Core::Profile::Sqlserver::Install/Dsc_xsqlserversetup[SQLMT]/ensure: change from absent to present f
ailed: PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource functionality with error messa
ge: 'SSMS' is not a valid value for setting 'FEATURES'.  Refer to SQL Help for more information..```

Thanks, and I can provide more information on request. 
Christopher

**Comment by jpogran** [comment]
Your original error message means that there was already a DSC job running when you attempted to run another. This typically happens when you try to cancel an interactive DSC run but it continues to run, or if a DSC run continues to run but is in a hung state. You would either need to kill the DSC process or restart the server at that point.

As for the current error message, you are specifying a value that the DSC Resource is not expecting. We are working on making a new build of the dsc module available with updated resources, see #272 for more information. If you can't wait until then you can follow the https://github.com/puppetlabs/puppetlabs-dsc/blob/master/README_BUILD.md guide for more information on how to build it yourself.

**Comment by marcinbojko** [comment]
@jpogran It's another opportunity for my 3 cents :)
It would be really helpfull to have available montly 'stable' builds of puppelabs-dsc. Custom,own builds are cool, but i can imagine issues hell, when stable releases will be not so frequent and popular way of getting modules with fixed content would force us to make own build.
Puppetlabs-dsc looks for me like core module for all WIndows based systems, so I would really like to have it in a top shape.
SO, please, please, please - reconsider making stable builds at specific intervals (month?, bi-month?)

**Comment by jpogran** [comment]
@marcinbojko We always appreciate feedback, and this sort of feedback helps up prioritize. If you could copy/paste what you just wrote and make a ticket in our [jira](https://tickets.puppetlabs.com/secure/CreateIssue!default.jspa) under Forge-Modules, I have actionable feedback I can push up the change in command. Post the ticket number here as well.

**Comment by marcinbojko** [comment]
@jpogran It's already done.

**Comment by jpogran** [comment]
Apologies, too many plates. I'll pass that up the chain today

**Comment by marcinbojko** [comment]
I will be grateful.

**Comment by jpogran** [comment]
Hi,

Puppet will be shutting down the github issues tab in this repository as there already is a publicly accessible [issue tracker](https://tickets.puppetlabs.com/browse/MODULES) on March 24th, 20017.

If you want to continue the discussion from this issue, please follow the ticket already created from this issue (typically MODULES-XXXX) in our issue tracker.

If you would like to file a new issue, please follow the [template here](https://tickets.puppetlabs.com/CreateIssue.jspa?pid=10707) to create a new ticket.

Thanks,

James Pogran

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.\n\nWe're going to close it but please do raise another issue if the issue still persists. 😄
