### ISSUE TITLE
Help compiling custom DSC resource using hashtable

### ISSUE THREAD

**Issue by bsmienk** [puppetlabs/puppetlabs-dsc#285]
Currently I am creating multiple custom DSC resources to configure a Microsoft WDS server (as I could not find an existing DSC resource for that). I am trying to manage this WDS server using the puppet - dsc combination thanks to the puppetlabs-dsc module.

I have created some DSC resources that could be compiled into ruby types succesfully. However I am running into trouble when I try to use hashtables in my custom DSC resource. First I had to find out how to describe the hashtable in the SCHEMA file. 

Apparently a MOF file does not know how to handle hashtables and I have been looking around to find out how to use a hashtable in a DSC resource. I found 2 sources with similar answers:
http://stackoverflow.com/questions/26762169/how-correct-write-parameter-in-powershell-dsc
https://powershell.org/forums/topic/hashtable-as-resource-parameter/

You can find the module I have the issue with here:
https://github.com/bsmienk/custom_dsc_modules/tree/master/xCMC_WDS/DSCResources/Configure_WDS

In my schema.mof file I have the following line:
`[Required, EmbeddedInstance("MSFT_KeyValuePair")] String ConfigHash[];`

In my psm1 file I have the following line:
`[Parameter(Mandatory=$True)][ValidateNotNullOrEmpty()][Microsoft.Management.Infrastructure.CimInstance[]]$ConfigHash`

In my puppet profile I have the following lines:
`$wds_configuration              =   { "Answer clients: Yes"                     =>  "/AnswerClients:All" }`
```
  dsc_configure_wds{'StandardConfiguration':
    dsc_configurationname         =>  'StandardConfiguration',
    dsc_confighash                =>  $wds_configuration
  }
```

Creating the types works fine, but when I try to apply the configuration I get the following error:

```
Error: /Stage[main]/Profile::Wds::Server/Dsc_configure_wds[StandardConfiguration]: Could not evaluate: Exception calling
 "EndInvoke" with "1" argument(s): "One or more parameter values passed to the method were invalid."
```

So now I am wondering: Should I avoid using hashtables at all? Or am I doing something wrong here?

**Comment by jpogran** [comment]
You should be able to use hashtables. Thank you for the complete repo of your use case, I will be able to investigate without any problem, but I won't be able to get to it till later today my time. If you are able, can you post what a interactive `puppet apply --debug` outputs here? If not, when I get out of meetings today I can build the types and run them myself

**Comment by bsmienk** [comment]
Hello jpogran,

I have tried using that command, however I am getting an error.
```
C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/environments.rb:38:in `get!': Could not find a
directory environment named 'puppetdev' anywhere in the path: C:/ProgramData/PuppetLabs/code/environments. Does the
directory exist? (Puppet::Environments::EnvironmentNotFound)
        from C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/application_support.rb:29:in `pus
_application_context'
        from C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/application.rb:337:in `run'
        from C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
        from C:/Program Files/Puppet Labs/Puppet/sys/ruby/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execu
e'
        from C:/Program Files/Puppet Labs/Puppet/puppet/bin/puppet:4:in `<main>'
```

My puppet client has been assigned to a environment called 'puppetdev', and I checked the directory "C:/ProgramData/PuppetLabs/code/environments" and I only found a 'production' directory there. Unfortunately I am no puppet expert, but I do know that puppet has been functioning fine without this 'puppetdev' directory.

**Comment by jpogran** [comment]
No worries. Your setup with environments so testing with that interactively takes a little more work. I can work on a repo over here and let you know today.

**Comment by jpogran** [comment]
When the dsc module runs it takes the code in your puppet manifest and converts that into PowerShell code that invokes the DSC engine directly using `Invoke-DscResource`. We can see the result of this by running puppet interactively, e.g. `puppet apply --debug`. It will output the PowerShell code that is sending the data to DSC to execute. When I did that with your DSC Resource, I got the following:

```
$invokeParams = @{
  Name          = 'Configure_WDS'
  Method        = 'test'
  Property      = @{
    configurationname = 'StandardConfiguration'
    confighash = [CimInstance](New-CimInstance -ClassName 'MSFT_KeyValuePair' -ClientOnly -Property @{'Answer clients: Yes' = '/AnswerClients:All'})
  }
  ModuleName = @{
    ModuleName      = "C:/puppetlabs/modules/dsc/lib/puppet_x/dsc_resources/xCMC_WDS/xCMC_WDS.psd1"
    RequiredVersion = "1.0"
  }
}
```

This shows us that there wasn't any problem parsing your manifest and turning it into a command to send to DSC. For the most part, since PowerShell and Puppet are so similar in most data types, there isn't much impedence mismatch when converting. Hashes translate mostly without much fuss, a good example is the PSCredential parameter, so it isn't much of a suprise that it generated syntatically correct PowerShell code. The stumbling point here is:

```
[CimInstance](New-CimInstance -ClassName 'MSFT_KeyValuePair' -ClientOnly -Property @{'Answer clients: Yes' = '/AnswerClients:All'})
```

The `Property` parameter is a C# Dictionary, and it converts PowerShell hashes to dictionaries for you. Normally .NET Dictionaries accept spaces or other special characters in keys, but `New-CimInstance` is creating typed properties it can serialize and so it seems to expect keys without special characters. Removing the space and the colon allows the hashtable to be parsed and then the DSC run continues past the parsing stage, but I can't test further as I don't have a WDS setup. This unfortunatly means that we (the dsc module) can't accept that key as a value. 

What I would suggest here instead of pursing a way to make puppet or dsc accept a key like this, is to take a step back and look at how you are desigining your DSC Resource. Both puppet and dsc, and all configuration management tools, share a concept of seperating configuration data (the what) from the configuration code (the how). In other words, as a user of a DSC Resource you should be able to specify only the data that is needed to set a target node to the state you want, you shouldn't have to know the code required to do so. The way you have your DSC Resource designed now, you have to know a specific search string as well as the acceptable values to change it to. It makes for a neat PowerShell one-liner, but makes for a very hard user experience. It also makes it hard to 'see' what is changing on a system. The data `'Answer clients: Yes' = '/AnswerClients:All'` is hard to read and won't be easy to read in a change log in DSC or Puppet.

To address this I looked at the technet docs for wsdutil (never having used the tool myself) and found this https://technet.microsoft.com/en-us/library/cc816898(v=ws.11).aspx. It lists the parameters and values to configure a WDS Server. Looking at this long list, its apparant to me that for the most part it can be taken as a parameter statement for a DSC Resourcce. The DSC Resource now looks like:

```
Function Set-TargetResource {
  Param(
    [Parameter()]
    [ValidateSet('All', 'Known', 'None')]
    [string]$AnswerClients,

    [Parameter()]
    [ValidateSet('Yes', 'No')]
    [string]$RogueDetection,
  )

  # there are a few ways to approach this,
  # this is an example of one approach
  # you could index on PsBoundParameters and dynamically get the 
  # key name and value without hardcoding. Its up to you how intricate
  # you want to get
  if($PsBoundParameters.ContainsKey('AnswerClients')){
    try{
      Invoke-Expression -command "wdsutil.exe /set-server /AnswerClients:$($AnswerClients)"
    }catch{
      #return error
    }
  }
  # repeat for RogueDetection
}  
```

And your manifest now looks like the following:

```
dsc_configure_wds{'StandardConfiguration':
  dsc_roguedetection    => 'No'
  dsc_answerclients     => 'All'
}
```

It's easy to see now what properties are being set and what they are being set to. Because of the typed DSC Resource parameters, they are picked up on building the types and are available in the puppet types for validation and use.

```
newparam(:dsc_answerclients) do
  def mof_type; 'string' end
  def mof_is_embedded?; false end
  desc "Answerclients - Valid values are Yes, No, All."
  validate do |value|
    resource[:ensure] = value.downcase
    unless value.kind_of?(String)
      fail("Invalid value '#{value}'. Should be a string")
    end
    unless ['Yes', 'yes', 'No', 'no', 'All','all'].include?(value)
      fail("Invalid value '#{value}'. Valid values are Yes, No, All")
    end
  end
end
```

**Comment by bsmienk** [comment]
Thanks a lot for taking all this time to analyze this issue. You are awesome!

You are completely right about the DSC resource design, it is not practical and only made to push an entire WDS configuration in one resource. I had already been thinking about dropping the hashtable and just create a bunch of new dsc resources that will change some specific settings. That way, whoever ends up using it, doesn't have to study the wdsutils page you linked.

In the end I was more interested in finding out if hashtables (or KeyValuePairs) are working in the puppet-dsc method and I am glad that it does. I will avoid using special characters in the keys though.

I will close this issue.
Thanks again!
